import { Match } from "./types";

export const matches: Match[] = [
  {
    id: "match-1",
    competition: "Liga 1 Indonesia",
    date: "2026-05-07",
    time: "19:00",
    status: "finished",
    venue: "Gelora Bung Karno, Jakarta",
    matchDay: 28,
    score: { home: 2, away: 1 },
    homeTeam: {
      teamName: "Persija Jakarta",
      teamLogo: "🔴",
      teamColor: "#E53E3E",
      formation: "4-3-3",
      players: [
        { id: "p1", name: "Andritany Ardhiyasa", number: 1, position: "GK", x: 50, y: 90 },
        { id: "p2", name: "Hansamu Yama", number: 3, position: "DEF", x: 20, y: 70 },
        { id: "p3", name: "Ryuji Utomo", number: 5, position: "DEF", x: 40, y: 72 },
        { id: "p4", name: "Alfath Faathier", number: 2, position: "DEF", x: 60, y: 72 },
        { id: "p5", name: "Firza Andika", number: 12, position: "DEF", x: 80, y: 70 },
        { id: "p6", name: "Rohit Chand", number: 15, position: "MID", x: 30, y: 50 },
        { id: "p7", name: "Marc Klok", number: 8, position: "MID", x: 50, y: 48 },
        { id: "p8", name: "Hanno Behrens", number: 10, position: "MID", x: 70, y: 50 },
        { id: "p9", name: "Riko Simanjuntak", number: 7, position: "FWD", x: 20, y: 25 },
        { id: "p10", name: "Marko Simic", number: 9, position: "FWD", x: 50, y: 20 },
        { id: "p11", name: "Taufik Hidayat", number: 11, position: "FWD", x: 80, y: 25 },
      ],
      substitutes: [
        { id: "p12", name: "Shahar Ginanjar", number: 30, position: "GK", x: 0, y: 0 },
        { id: "p13", name: "Maman Abdurahman", number: 20, position: "MID", x: 0, y: 0 },
        { id: "p14", name: "Rezaldi Hehanusa", number: 22, position: "DEF", x: 0, y: 0 },
        { id: "p15", name: "Osvaldo Haay", number: 17, position: "FWD", x: 0, y: 0 },
        { id: "p16", name: "Sandi Sute", number: 25, position: "MID", x: 0, y: 0 },
      ],
    },
    awayTeam: {
      teamName: "Persib Bandung",
      teamLogo: "🔵",
      teamColor: "#3B82F6",
      formation: "4-4-2",
      players: [
        { id: "p17", name: "Teja Paku Alam", number: 1, position: "GK", x: 50, y: 90 },
        { id: "p18", name: "Ardi Idrus", number: 3, position: "DEF", x: 20, y: 70 },
        { id: "p19", name: "Victor Igbonefo", number: 4, position: "DEF", x: 40, y: 72 },
        { id: "p20", name: "Nick Kuipers", number: 5, position: "DEF", x: 60, y: 72 },
        { id: "p21", name: "Dedi Kusnandar", number: 2, position: "DEF", x: 80, y: 70 },
        { id: "p22", name: "Beckham Putra", number: 7, position: "MID", x: 20, y: 50 },
        { id: "p23", name: "David da Silva", number: 10, position: "MID", x: 40, y: 48 },
        { id: "p24", name: "Febri Hariyadi", number: 11, position: "MID", x: 60, y: 48 },
        { id: "p25", name: "Frets Butuan", number: 8, position: "MID", x: 80, y: 50 },
        { id: "p26", name: "Ciro Alves", number: 9, position: "FWD", x: 40, y: 22 },
        { id: "p27", name: "Wander Luiz", number: 20, position: "FWD", x: 60, y: 22 },
      ],
      substitutes: [
        { id: "p28", name: "Dhika Bayangkara", number: 30, position: "GK", x: 0, y: 0 },
        { id: "p29", name: "Zalnando", number: 14, position: "DEF", x: 0, y: 0 },
        { id: "p30", name: "Erwin Ramdani", number: 16, position: "MID", x: 0, y: 0 },
        { id: "p31", name: "Ezra Walian", number: 19, position: "FWD", x: 0, y: 0 },
        { id: "p32", name: "Bayu Fiqri", number: 23, position: "DEF", x: 0, y: 0 },
      ],
    },
    events: [
      { id: "e1", type: "goal", minute: 12, player: "Marko Simic", team: "home", assistBy: "Riko Simanjuntak" },
      { id: "e2", type: "yellow_card", minute: 23, player: "Hansamu Yama", team: "home" },
      { id: "e3", type: "goal", minute: 34, player: "Ciro Alves", team: "away", assistBy: "Febri Hariyadi" },
      { id: "e4", type: "yellow_card", minute: 41, player: "Nick Kuipers", team: "away" },
      { id: "e5", type: "substitution", minute: 46, player: "Taufik Hidayat", team: "home", playerOut: "Osvaldo Haay" },
      { id: "e6", type: "goal", minute: 67, player: "Marc Klok", team: "home", assistBy: "Hanno Behrens" },
      { id: "e7", type: "yellow_card", minute: 72, player: "David da Silva", team: "away" },
      { id: "e8", type: "substitution", minute: 78, player: "Erwin Ramdani", team: "away", playerOut: "Frets Butuan" },
      { id: "e9", type: "red_card", minute: 88, player: "Ardi Idrus", team: "away" },
    ],
  },
  {
    id: "match-2",
    competition: "Liga 1 Indonesia",
    date: "2026-05-08",
    time: "19:30",
    status: "live",
    venue: "Kanjuruhan Stadium, Malang",
    matchDay: 28,
    score: { home: 1, away: 1 },
    homeTeam: {
      teamName: "Arema FC",
      teamLogo: "🦁",
      teamColor: "#2D6A4F",
      formation: "4-2-3-1",
      players: [
        { id: "p33", name: "Kartika Ajie", number: 1, position: "GK", x: 50, y: 90 },
        { id: "p34", name: "Bagas Adi Nugroho", number: 4, position: "DEF", x: 20, y: 70 },
        { id: "p35", name: "Adilson Maringa", number: 3, position: "DEF", x: 40, y: 72 },
        { id: "p36", name: "Rizky Dwi Febrianto", number: 5, position: "DEF", x: 60, y: 72 },
        { id: "p37", name: "Hendro Siswanto", number: 2, position: "DEF", x: 80, y: 70 },
        { id: "p38", name: "Jayus Hariono", number: 6, position: "MID", x: 35, y: 55 },
        { id: "p39", name: "Evan Dimas", number: 8, position: "MID", x: 65, y: 55 },
        { id: "p40", name: "M. Rafli", number: 7, position: "MID", x: 20, y: 38 },
        { id: "p41", name: "Rizky Pellu", number: 10, position: "MID", x: 50, y: 35 },
        { id: "p42", name: "Kushedya Hari K.", number: 11, position: "MID", x: 80, y: 38 },
        { id: "p43", name: "Matheus Cunha", number: 9, position: "FWD", x: 50, y: 18 },
      ],
      substitutes: [
        { id: "p44", name: "Felipe Americo", number: 30, position: "GK", x: 0, y: 0 },
        { id: "p45", name: "Ahmad Bustomi", number: 15, position: "MID", x: 0, y: 0 },
        { id: "p46", name: "Dedik Setiawan", number: 19, position: "FWD", x: 0, y: 0 },
        { id: "p47", name: "M. Sihran", number: 22, position: "DEF", x: 0, y: 0 },
        { id: "p48", name: "Irsyad Maulana", number: 25, position: "MID", x: 0, y: 0 },
      ],
    },
    awayTeam: {
      teamName: "Persebaya Surabaya",
      teamLogo: "🐊",
      teamColor: "#16A34A",
      formation: "4-3-3",
      players: [
        { id: "p49", name: "Ernando Ari", number: 1, position: "GK", x: 50, y: 90 },
        { id: "p50", name: "Rizky Ridho", number: 3, position: "DEF", x: 20, y: 70 },
        { id: "p51", name: "Wellington Carvalho", number: 4, position: "DEF", x: 40, y: 72 },
        { id: "p52", name: "Hugo Gomes", number: 5, position: "DEF", x: 60, y: 72 },
        { id: "p53", name: "Rachmat Irianto", number: 2, position: "DEF", x: 80, y: 70 },
        { id: "p54", name: "Bruno Moreira", number: 6, position: "MID", x: 30, y: 50 },
        { id: "p55", name: "Sho Yamamoto", number: 8, position: "MID", x: 50, y: 48 },
        { id: "p56", name: "Marselino Ferdinan", number: 10, position: "MID", x: 70, y: 50 },
        { id: "p57", name: "Jose Wilkson", number: 7, position: "FWD", x: 20, y: 25 },
        { id: "p58", name: "Ricky Kambuaya", number: 9, position: "FWD", x: 50, y: 20 },
        { id: "p59", name: "Samsul Arif", number: 11, position: "FWD", x: 80, y: 25 },
      ],
      substitutes: [
        { id: "p60", name: "Miswar", number: 30, position: "GK", x: 0, y: 0 },
        { id: "p61", name: "Rendi Irwan", number: 14, position: "DEF", x: 0, y: 0 },
        { id: "p62", name: "Ahmad Ngafe", number: 16, position: "MID", x: 0, y: 0 },
        { id: "p63", name: "Makan Konate", number: 19, position: "FWD", x: 0, y: 0 },
        { id: "p64", name: "Hambali Tolib", number: 23, position: "MID", x: 0, y: 0 },
      ],
    },
    events: [
      { id: "e10", type: "goal", minute: 15, player: "Matheus Cunha", team: "home", assistBy: "Evan Dimas" },
      { id: "e11", type: "yellow_card", minute: 22, player: "Wellington Carvalho", team: "away" },
      { id: "e12", type: "goal", minute: 38, player: "Ricky Kambuaya", team: "away", assistBy: "Marselino Ferdinan" },
      { id: "e13", type: "yellow_card", minute: 45, player: "Adilson Maringa", team: "home" },
    ],
  },
  {
    id: "match-3",
    competition: "Liga 1 Indonesia",
    date: "2026-05-09",
    time: "19:00",
    status: "upcoming",
    venue: "Kapten I Wayan Dipta, Bali",
    matchDay: 28,
    score: { home: 0, away: 0 },
    homeTeam: {
      teamName: "Bali United",
      teamLogo: "🏝️",
      teamColor: "#DC2626",
      formation: "3-5-2",
      players: [
        { id: "p65", name: "Wawan Hendrawan", number: 1, position: "GK", x: 50, y: 90 },
        { id: "p66", name: "Willian Pacheco", number: 3, position: "DEF", x: 25, y: 72 },
        { id: "p67", name: "Andhika Wijaya", number: 5, position: "DEF", x: 50, y: 74 },
        { id: "p68", name: "Ricky Fajrin", number: 4, position: "DEF", x: 75, y: 72 },
        { id: "p69", name: "Eber Bessa", number: 2, position: "MID", x: 10, y: 50 },
        { id: "p70", name: "Brwa Nouri", number: 6, position: "MID", x: 30, y: 52 },
        { id: "p71", name: "Fadil Sausu", number: 8, position: "MID", x: 50, y: 48 },
        { id: "p72", name: "Paulo Sitanggang", number: 10, position: "MID", x: 70, y: 52 },
        { id: "p73", name: "Rizky Pellu", number: 7, position: "MID", x: 90, y: 50 },
        { id: "p74", name: "Ilija Spasojevic", number: 9, position: "FWD", x: 35, y: 22 },
        { id: "p75", name: "Lerby Eliandry", number: 11, position: "FWD", x: 65, y: 22 },
      ],
      substitutes: [
        { id: "p76", name: "Samuel Reimas", number: 30, position: "GK", x: 0, y: 0 },
        { id: "p77", name: "M. Sidik Saimima", number: 14, position: "DEF", x: 0, y: 0 },
        { id: "p78", name: "M. Ridwan", number: 17, position: "MID", x: 0, y: 0 },
        { id: "p79", name: "Rahmat Arjuna", number: 19, position: "FWD", x: 0, y: 0 },
        { id: "p80", name: "Kadek Agung", number: 22, position: "MID", x: 0, y: 0 },
      ],
    },
    awayTeam: {
      teamName: "PSM Makassar",
      teamLogo: "⚓",
      teamColor: "#EA580C",
      formation: "4-4-2",
      players: [
        { id: "p81", name: "Hilman Syah", number: 1, position: "GK", x: 50, y: 90 },
        { id: "p82", name: "Erwin Gutawa", number: 3, position: "DEF", x: 20, y: 70 },
        { id: "p83", name: "Dias Angga Putra", number: 4, position: "DEF", x: 40, y: 72 },
        { id: "p84", name: "Hasyim Kipuw", number: 5, position: "DEF", x: 60, y: 72 },
        { id: "p85", name: "Asnawi Mangkualam", number: 2, position: "DEF", x: 80, y: 70 },
        { id: "p86", name: "Sutanto Tan", number: 7, position: "MID", x: 20, y: 50 },
        { id: "p87", name: "Pluim Valencijn", number: 8, position: "MID", x: 40, y: 48 },
        { id: "p88", name: "Yakob Sayuri", number: 10, position: "MID", x: 60, y: 48 },
        { id: "p89", name: "Ilham Udin Armaiyn", number: 11, position: "MID", x: 80, y: 50 },
        { id: "p90", name: "Anco Jansen", number: 9, position: "FWD", x: 40, y: 22 },
        { id: "p91", name: "Ramadhan Sananta", number: 20, position: "FWD", x: 60, y: 22 },
      ],
      substitutes: [
        { id: "p92", name: "Rivky Mokodompit", number: 30, position: "GK", x: 0, y: 0 },
        { id: "p93", name: "Kazuaki Takitani", number: 14, position: "DEF", x: 0, y: 0 },
        { id: "p94", name: "Rasyid Bakri", number: 16, position: "MID", x: 0, y: 0 },
        { id: "p95", name: "M. Arfan", number: 19, position: "DEF", x: 0, y: 0 },
        { id: "p96", name: "Rahul Pratama", number: 23, position: "MID", x: 0, y: 0 },
      ],
    },
    events: [],
  },
  {
    id: "match-4",
    competition: "Liga 1 Indonesia",
    date: "2026-05-09",
    time: "19:30",
    status: "upcoming",
    venue: "Jatidiri Stadium, Semarang",
    matchDay: 28,
    score: { home: 0, away: 0 },
    homeTeam: {
      teamName: "PSIS Semarang",
      teamLogo: "⚓",
      teamColor: "#2563EB",
      formation: "4-2-3-1",
      players: [
        { id: "p97", name: "Joko Ribowo", number: 1, position: "GK", x: 50, y: 90 },
        { id: "p98", name: "Riyan Ardiansyah", number: 3, position: "DEF", x: 20, y: 70 },
        { id: "p99", name: "Wallace Costa", number: 4, position: "DEF", x: 40, y: 72 },
        { id: "p100", name: "Fredyan Wahyu", number: 5, position: "DEF", x: 60, y: 72 },
        { id: "p101", name: "Pratama Arhan", number: 2, position: "DEF", x: 80, y: 70 },
        { id: "p102", name: "Taisei Marukawa", number: 6, position: "MID", x: 35, y: 55 },
        { id: "p103", name: "Hari Nur Yulianto", number: 8, position: "MID", x: 65, y: 55 },
        { id: "p104", name: "Finky Pasamba", number: 7, position: "MID", x: 20, y: 38 },
        { id: "p105", name: "Jonathan Cantillana", number: 10, position: "MID", x: 50, y: 35 },
        { id: "p106", name: "Rishadi Fauzi", number: 11, position: "MID", x: 80, y: 38 },
        { id: "p107", name: "Bruno Silva", number: 9, position: "FWD", x: 50, y: 18 },
      ],
      substitutes: [
        { id: "p108", name: "Jandia", number: 30, position: "GK", x: 0, y: 0 },
        { id: "p109", name: "Rizky Setiawan", number: 14, position: "DEF", x: 0, y: 0 },
        { id: "p110", name: "M. Hidayat", number: 16, position: "MID", x: 0, y: 0 },
        { id: "p111", name: "Ramadhan Sananta", number: 19, position: "FWD", x: 0, y: 0 },
        { id: "p112", name: "Seto Hari", number: 22, position: "MID", x: 0, y: 0 },
      ],
    },
    awayTeam: {
      teamName: "Madura United",
      teamLogo: "🐂",
      teamColor: "#DC2626",
      formation: "4-3-3",
      players: [
        { id: "p113", name: "Ridho Djazulie", number: 1, position: "GK", x: 50, y: 90 },
        { id: "p114", name: "Jaimerson Da Silva", number: 3, position: "DEF", x: 20, y: 70 },
        { id: "p115", name: "Fachruddin Aryanto", number: 4, position: "DEF", x: 40, y: 72 },
        { id: "p116", name: "Dodi Alekvan", number: 5, position: "DEF", x: 60, y: 72 },
        { id: "p117", name: "Novan Setya", number: 2, position: "DEF", x: 80, y: 70 },
        { id: "p118", name: "Rafiuddin", number: 6, position: "MID", x: 30, y: 50 },
        { id: "p119", name: "Kevy Syahputra", number: 8, position: "MID", x: 50, y: 48 },
        { id: "p120", name: "Lulinha", number: 10, position: "MID", x: 70, y: 50 },
        { id: "p121", name: "Rafael Silva", number: 7, position: "FWD", x: 20, y: 25 },
        { id: "p122", name: "Alberto Goncalves", number: 9, position: "FWD", x: 50, y: 20 },
        { id: "p123", name: "Kevy Sahertian", number: 11, position: "FWD", x: 80, y: 25 },
      ],
      substitutes: [
        { id: "p124", name: "M. Riyandi", number: 30, position: "GK", x: 0, y: 0 },
        { id: "p125", name: "Zulham Zamrun", number: 14, position: "FWD", x: 0, y: 0 },
        { id: "p126", name: "Andri Muliadi", number: 16, position: "MID", x: 0, y: 0 },
        { id: "p127", name: "Benny Wahyudi", number: 19, position: "DEF", x: 0, y: 0 },
        { id: "p128", name: "M. Syahid", number: 23, position: "MID", x: 0, y: 0 },
      ],
    },
    events: [],
  },
];
